name: Update Profile

permissions:
  contents: write

on:
  schedule:
    # 每天北京时间 01:00 = UTC 17:00
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      MY_GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
      MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}   # classic PAT，勾 repo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install requests

      - name: Run update.py
        run: python ./update.py

      - name: Commit & push with rebase
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ -n "$(git status --porcelain README.md)" ]]; then
            git add README.md
            git commit -m ":book: update by GitHub Actions" || true
          else
            echo "No changes to commit"
          fi

          BRANCH="${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
          git fetch origin "${BRANCH}"
          git pull --rebase origin "${BRANCH}"
          git push origin "${BRANCH}"
